package com.example.morawallet.data.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.example.morawallet.R
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.android.libraries.identity.googleid.GoogleIdTokenParsingException

/** Outcome of asking Credential Manager for a Google ID token. */
sealed interface GoogleTokenResult {
    data class Success(val idToken: String) : GoogleTokenResult

    /** User dismissed the Google account chooser — not an error worth showing. */
    data object Cancelled : GoogleTokenResult

    data class Failure(val message: String) : GoogleTokenResult
}

/**
 * Wraps the AndroidX Credential Manager flow that produces a Google ID token.
 *
 * Must be created with an Activity [Context] (e.g. `LocalContext.current` inside a screen),
 * because the credential picker is shown as UI on top of it.
 */
class GoogleAuthClient(private val context: Context) {

    private val credentialManager = CredentialManager.create(context)

    suspend fun getIdToken(): GoogleTokenResult {
        // default_web_client_id is generated by the google-services plugin from the
        // web (client_type 3) entry in google-services.json — not the Android client.
        val option = GetSignInWithGoogleOption.Builder(
            context.getString(R.string.default_web_client_id),
        ).build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(option)
            .build()

        return try {
            val response = credentialManager.getCredential(context, request)
            val credential = response.credential
            if (credential is androidx.credentials.CustomCredential &&
                credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
            ) {
                val googleCredential = GoogleIdTokenCredential.createFrom(credential.data)
                GoogleTokenResult.Success(googleCredential.idToken)
            } else {
                GoogleTokenResult.Failure("Unexpected credential type from Google.")
            }
        } catch (e: GetCredentialCancellationException) {
            GoogleTokenResult.Cancelled
        } catch (e: NoCredentialException) {
            GoogleTokenResult.Failure("No Google account available on this device.")
        } catch (e: GoogleIdTokenParsingException) {
            GoogleTokenResult.Failure("Could not read Google credentials. Please try again.")
        } catch (e: GetCredentialException) {
            GoogleTokenResult.Failure(e.localizedMessage ?: "Google sign-in failed.")
        }
    }
}
